[package]
name = "swissmedicinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.36"
csv = "1.3"
chrono = "0.4"
reqwest = { version = "0.12", features = ["blocking", "cookies"] }
scraper = "0.20"
urlencoding = "2.1"
zip = "2.2"
